apiVersion: batch/v1
kind: Job
metadata:
  name: a
  namespace: dholmber
spec:
  completions: 2
  parallelism: 2
  completionMode: Indexed
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      initContainers:
      - name: 'input'
        image: 'docker.io/library/bash'
        command:
        - "bash"
        - "-c"
        - |
          items=("s3://jec-data/test/120.root" "s3://jec-data/test/121.root")
          echo -n ${items[$JOB_COMPLETION_INDEX]} > /input/data.txt          
        volumeMounts:
        - mountPath: /input
          name: input
      containers:
      - name: jec-inference
        image: registry.cern.ch/ml/jec-inference:latest
        command: ["python3",  "inference.py", "--file=/input/data.txt"]
        volumeMounts:
        - mountPath: /input
          name: input
      volumes:
      - name: input
        emptyDir: {}